language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud: true

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=jowi20 -Dsonar.login=$SONAR_TOKEN -X
  - pytest

notifications:
  slack: entornodeinte-7kl4185:CzpWZiwwkKRTQvjVTFFRgqIt

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: d16b85e5-8e41-4a20-8bb5-5a007ab1d693
  app: myapp
  on:
    repo: jowi20/MiEntornoIC